name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4
    
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
     - uses: actions/checkout@v1
     - name: Setup PostgreSQL
       uses: Harmon758/postgresql-action@v1.0.0
       with:
           # POSTGRES_DB - name for the default database that is created
           postgresql db: philomena_test
           # POSTGRES_USER - create the specified user with superuser power
           postgresql user: postgres # optional, default is 
           # POSTGRES_PASSWORD - superuser password
           postgresql password: postgres
          
     - name: Install Dependencies
       run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
     - name: Run Tests
       run: mix test
